---
- name: Create user.
  become: yes
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default(admin_groups)}}"
    shell: /bin/bash
  with_items: "{{ admin_users }}"

- name: Set authorized key.
  become: yes
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_keys}}"
  with_items: "{{ admin_users}}"

- name: Check for sudoers file
  stat:
    path: /etc/sudoers.d/90-cloud-init-users
  register: cloud_sudoers_file

- name: Set passwordless sudo.
  become: yes
  lineinfile:
    dest: /etc/sudoers.d/90-cloud-init-users
    state: present
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  with_items: "{{ admin_users }}"
  when: cloud_sudoers_file.stat.exists == True

- name: Check for sshd config
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_file

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh
  when: sshd_config_file.stat.exists == True
